<Project Sdk="Microsoft.NET.Sdk">
  <Import
    Project="$(MSBuildUserExtensionsPath)/sdv.props"
    Condition="Exists('$(MSBuildUserExtensionsPath)/sdv.props')"
  />

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
    <EnableHarmony>true</EnableHarmony>
    <ModZipPath>$(MSBuildThisFileDirectory)/../_releases</ModZipPath>
  </PropertyGroup>

  <PropertyGroup>
    <Name>Mod Name Tooltip</Name>
    <Authors>mushymato</Authors>
    <Description>Shows the mod name of items via tooltip and provide API</Description>
    <UniqueId>mushymato.ModNameTooltip</UniqueId>
    <UpdateKeys>Nexus:50688,GitHub:Mushymato/ModNameTooltip</UpdateKeys>
    <Version>1.4.1</Version>
    <BaseManifest>new</BaseManifest>
    <MinimumApiVersion_Behavior>Update</MinimumApiVersion_Behavior>
    <MinimumGameVersion_Behavior>UpdateFull</MinimumGameVersion_Behavior>
    <Dependencies_VersionBehavior>Ignore</Dependencies_VersionBehavior>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Leclair.Stardew.ModManifestBuilder" Version="2.4.1" />
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
    <PackageReference Include="Pathoschild.Stardew.ModTranslationClassBuilder" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Publicize Include="StardewModdingAPI" />
  </ItemGroup>
</Project>
